FROM node:latest
ARG ssh_prv_key
ARG ssh_pub_key
RUN apt-get update && apt-get install -y git
RUN mkdir -p /root/.ssh && \
    chmod 0700 /root/.ssh && \
    ssh-keyscan github.com > /root/.ssh/known_hosts
RUN echo "$ssh_prv_key" > /root/.ssh/id_rsa && \
    echo "$ssh_pub_key" > /root/.ssh/id_rsa.pub && \
    chmod 700 /root/.ssh/id_rsa && \
    chmod 700 /root/.ssh/id_rsa.pub
RUN git clone https://github.com/ermine2001/easy-sauce.git
RUN npm install -g eslint@latest --save-dev && \
    npm install eslint-config-google --save-dev
WORKDIR /easy-sauce
